include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    cascade_invocations: false
    discarded_futures: true


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options